name: Terraform Pipeline
description: A GitHub Actions workflow to run Terraform plan and apply on push to main branch.

on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Terraform Init
        run: |
          terraform init
        shell: bash

      - name: Run Terraform Plan
        run: |
          terraform plan
        shell: bash

      - name: Run Terraform Apply
        run: |
          terraform apply -auto-approve
        shell: bash